author: dennyrwa
name: Kedai Kosim
judul: Kedai Kopi di Tulungagung
address: Jl. Wahid Hasyim No. 62 (Barat perempatan 555) Tulungagung
image-logo-1: assets/img/kedai-kosim-logo-lingkaran.png
image-logo-2: assets/img/kedai-kosim-logo-segi-enam.png
description: Kedai Kopi Siang Malam atau yang lebih dikenal dengan Kedai Kosim adalah cafe yang terletak di pusat kota Tulungagung dengan konsep Manual Brewing yang menjual aneka kopi teh cokelat berkualitas dengan harga yang sangat terjangkau.
description-2: Kedai Kopi Siang Malam atau yang lebih sering dikenal dengan <strong>Kedai Kosim</strong> terletak di jantung kota Tulungagung, tepatnya di Jl. Wahid Hasyim No. 62 (Barat perempatan 555) Tulungagung. Kedai Kopi ini menyediakan berbagai macam varian kopi nusantara seperti kopi Toraja, Wamena, Sidikalang, Mandheling, Lampung, Kintamani dan sebagainya. Pecinta kopi, Penasaran? Kunjungi ke <strong>Kedai Kosim</strong>.
keywords: Kedai Kopi di Tulungagung, Cafe di Tulungagung, Kafe di Tulungagung
exclude: [README.md]
fb_app_id:
facebook: kedaikosim
instagram: kedaikosim
twittersite: kedaikosim
favicon: /assets/img/favicon.png
permalink: pretty
permalink: /404.html
siteurl: https://kedaikosim.com
baseurl:
collections:
  data-kopi:
  data-teh:
  data-coklat:
  data-vlog:
  data-event:
  data-header-slider:
  data-merchandise:
  data-kemitraan:
  data-dropship:
